image: hwrunner:latest
variables:
    GIT_SSL_NO_VERIFY: "true"
    EXEC: dtmf
    HW_DIR: hw1
before_script:
    - make clean all -C ${HW_DIR}
stages:
    - build
    - run
    - test
build:
    stage: build
    script:
        - echo "Build done"
run:
    stage: run
    script:
        - cd ${HW_DIR} && bin/${EXEC} -h
test:
    stage: test
    script:
        - cd ${HW_DIR} && bin/${EXEC}_tests -S --verbose=0 --timeout 5
